/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Raw Event */
        post: operations["ingest_raw_event_v1_events_raw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents/{incident_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Incident */
        post: operations["transition_incident_v1_incidents__incident_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents/{incident_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Note */
        post: operations["add_note_v1_incidents__incident_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Responses */
        get: operations["list_responses_v1_responses_get"];
        put?: never;
        /** Propose Response */
        post: operations["propose_response_v1_responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responses/{action_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Response */
        post: operations["execute_response_v1_responses__action_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responses/{action_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert Response */
        post: operations["revert_response_v1_responses__action_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lab/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lab Assets */
        get: operations["list_lab_assets_v1_lab_assets_get"];
        put?: never;
        /** Register Lab Asset */
        post: operations["register_lab_asset_v1_lab_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lab/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deregister Lab Asset */
        delete: operations["deregister_lab_asset_v1_lab_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attack/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attack Catalog */
        get: operations["get_attack_catalog_v1_attack_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["get_entity_v1_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Entity */
        get: operations["lookup_entity_v1_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detections */
        get: operations["list_detections_v1_detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wazuh/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wazuh Status */
        get: operations["wazuh_status_v1_wazuh_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Requests */
        get: operations["list_evidence_requests_v1_evidence_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-requests/{request_id}/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collect Evidence Request */
        post: operations["collect_evidence_request_v1_evidence_requests__request_id__collect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence-requests/{request_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Evidence Request */
        post: operations["dismiss_evidence_request_v1_evidence_requests__request_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blocked-observables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blocked Observables */
        get: operations["list_blocked_observables_v1_blocked_observables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionExecuted */
        ActionExecuted: {
            action: components["schemas"]["ActionSummary"];
            log: components["schemas"]["ActionLogSummary"];
        };
        /**
         * ActionKind
         * @enum {string}
         */
        ActionKind: "tag_incident" | "elevate_severity" | "flag_host_in_lab" | "quarantine_host_lab" | "invalidate_lab_session" | "block_observable" | "kill_process_lab" | "request_evidence";
        /** ActionLogSummary */
        ActionLogSummary: {
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Executed By */
            executed_by: string;
            /**
             * Result
             * @enum {string}
             */
            result: "ok" | "fail" | "skipped";
            /** Reason */
            reason: string | null;
        };
        /** ActionProposeIn */
        ActionProposeIn: {
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            kind: components["schemas"]["ActionKind"];
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /** ActionProposed */
        ActionProposed: {
            action: components["schemas"]["ActionSummary"];
        };
        /** ActionSummary */
        ActionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Classification
             * @enum {string}
             */
            classification: "auto_safe" | "suggest_only" | "reversible" | "disruptive";
            /** Classification Reason */
            classification_reason: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "proposed" | "executed" | "failed" | "skipped" | "reverted";
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Proposed By
             * @enum {string}
             */
            proposed_by: "system" | "analyst";
            /**
             * Proposed At
             * Format: date-time
             */
            proposed_at: string;
            last_log: components["schemas"]["ActionLogSummary"] | null;
        };
        /** AttackCatalog */
        AttackCatalog: {
            /** Version */
            version: string;
            /** Entries */
            entries: components["schemas"]["AttackEntry"][];
        };
        /** AttackEntry */
        AttackEntry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "tactic" | "technique" | "subtechnique";
            /** Parent */
            parent: string | null;
            /** Url */
            url: string;
        };
        /** AttackRef */
        AttackRef: {
            /** Tactic */
            tactic: string;
            /** Technique */
            technique: string;
            /** Subtechnique */
            subtechnique: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "rule_derived" | "correlator_inferred";
        };
        /** BlockedObservableList */
        BlockedObservableList: {
            /** Items */
            items: components["schemas"]["BlockedObservableOut"][];
        };
        /** BlockedObservableOut */
        BlockedObservableOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Value */
            value: string;
            /**
             * Blocked At
             * Format: date-time
             */
            blocked_at: string;
            /** Active */
            active: boolean;
        };
        /** DetectionItem */
        DetectionItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rule Id */
            rule_id: string;
            /**
             * Rule Source
             * @enum {string}
             */
            rule_source: "sigma" | "py";
            /** Rule Version */
            rule_version: string;
            severity_hint: components["schemas"]["Severity"];
            /** Confidence Hint */
            confidence_hint: string;
            /** Attack Tags */
            attack_tags: string[];
            /** Matched Fields */
            matched_fields: {
                [key: string]: unknown;
            };
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Incident Id */
            incident_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DetectionList */
        DetectionList: {
            /** Items */
            items: components["schemas"]["DetectionItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** DetectionRef */
        DetectionRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rule Id */
            rule_id: string;
            /**
             * Rule Source
             * @enum {string}
             */
            rule_source: "sigma" | "py";
            /** Rule Version */
            rule_version: string;
            severity_hint: components["schemas"]["Severity"];
            /** Confidence Hint */
            confidence_hint: string;
            /** Attack Tags */
            attack_tags: string[];
            /** Matched Fields */
            matched_fields: {
                [key: string]: unknown;
            };
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DetectionRuleSource
         * @enum {string}
         */
        DetectionRuleSource: "sigma" | "py";
        /** EntityDetail */
        EntityDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["EntityKind"];
            /** Natural Key */
            natural_key: string;
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Recent Events */
            recent_events: components["schemas"]["EntityTimelineEvent"][];
            /** Related Incidents */
            related_incidents: components["schemas"]["EntityIncidentSummary"][];
        };
        /** EntityIncidentSummary */
        EntityIncidentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            kind: components["schemas"]["IncidentKind"];
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["Severity"];
            /** Confidence */
            confidence: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EntityKind
         * @enum {string}
         */
        EntityKind: "user" | "host" | "ip" | "process" | "file" | "observable";
        /** EntityRef */
        EntityRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["EntityKind"];
            /** Natural Key */
            natural_key: string;
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /** Role In Incident */
            role_in_incident: string;
        };
        /** EntityTimelineEvent */
        EntityTimelineEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Kind */
            kind: string;
            /** Normalized */
            normalized: {
                [key: string]: unknown;
            };
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EventList */
        EventList: {
            /** Items */
            items: components["schemas"]["EventSummary"][];
            /** Total */
            total: number;
        };
        /** EventSummary */
        EventSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Source */
            source: string;
            /** Kind */
            kind: string;
            /** Dedupe Key */
            dedupe_key?: string | null;
        };
        /** EvidenceRequestList */
        EvidenceRequestList: {
            /** Items */
            items: components["schemas"]["EvidenceRequestOut"][];
        };
        /** EvidenceRequestOut */
        EvidenceRequestOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Target Host Entity Id */
            target_host_entity_id: string | null;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Collected At */
            collected_at: string | null;
            /** Payload Url */
            payload_url: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentDetail */
        IncidentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            kind: components["schemas"]["IncidentKind"];
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["Severity"];
            /** Confidence */
            confidence: string;
            /** Rationale */
            rationale: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Correlator Rule */
            correlator_rule: string;
            /** Correlator Version */
            correlator_version: string;
            /** Entities */
            entities: components["schemas"]["EntityRef"][];
            /** Detections */
            detections: components["schemas"]["DetectionRef"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEvent"][];
            /** Attack */
            attack: components["schemas"]["AttackRef"][];
            /** Actions */
            actions: components["schemas"]["ActionSummary"][];
            /** Transitions */
            transitions: components["schemas"]["TransitionRef"][];
            /** Notes */
            notes: components["schemas"]["NoteRef"][];
        };
        /**
         * IncidentKind
         * @enum {string}
         */
        IncidentKind: "identity_compromise" | "endpoint_compromise" | "identity_endpoint_chain" | "unknown";
        /** IncidentList */
        IncidentList: {
            /** Items */
            items: components["schemas"]["IncidentSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "new" | "triaged" | "investigating" | "contained" | "resolved" | "closed" | "reopened";
        /** IncidentSummary */
        IncidentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            kind: components["schemas"]["IncidentKind"];
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["Severity"];
            /** Confidence */
            confidence: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Entity Count */
            entity_count: number;
            /** Detection Count */
            detection_count: number;
            /** Event Count */
            event_count: number;
            /** Primary User */
            primary_user: string | null;
            /** Primary Host */
            primary_host: string | null;
        };
        /** LabAssetIn */
        LabAssetIn: {
            kind: components["schemas"]["LabAssetKind"];
            /** Natural Key */
            natural_key: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * LabAssetKind
         * @enum {string}
         */
        LabAssetKind: "user" | "host" | "ip" | "observable";
        /** LabAssetOut */
        LabAssetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Natural Key */
            natural_key: string;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** Notes */
            notes: string | null;
        };
        /** NoteIn */
        NoteIn: {
            /** Body */
            body: string;
        };
        /** NoteRef */
        NoteRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Body */
            body: string;
            /** Author */
            author: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RawEventAccepted */
        RawEventAccepted: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Dedup Hit */
            dedup_hit: boolean;
            /** Detections Fired */
            detections_fired?: string[];
            /** Incident Touched */
            incident_touched?: string | null;
        };
        /** RawEventIn */
        RawEventIn: {
            /**
             * Source
             * @enum {string}
             */
            source: "direct" | "seeder";
            /** Kind */
            kind: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
            /** Normalized */
            normalized: {
                [key: string]: unknown;
            };
            /** Dedupe Key */
            dedupe_key?: string | null;
        };
        /** ResponseList */
        ResponseList: {
            /** Items */
            items: components["schemas"]["ActionSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "low" | "medium" | "high" | "critical";
        /** TimelineEvent */
        TimelineEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Kind */
            kind: string;
            /**
             * Source
             * @enum {string}
             */
            source: "wazuh" | "direct" | "seeder";
            /** Normalized */
            normalized: {
                [key: string]: unknown;
            };
            /**
             * Role In Incident
             * @enum {string}
             */
            role_in_incident: "trigger" | "supporting" | "context";
            /** Entity Ids */
            entity_ids: string[];
        };
        /** TransitionIn */
        TransitionIn: {
            to_status: components["schemas"]["IncidentStatus"];
            /** Reason */
            reason?: string | null;
        };
        /** TransitionOut */
        TransitionOut: {
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            from_status: components["schemas"]["IncidentStatus"] | null;
            to_status: components["schemas"]["IncidentStatus"];
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** TransitionRef */
        TransitionRef: {
            from_status: components["schemas"]["IncidentStatus"] | null;
            to_status: components["schemas"]["IncidentStatus"];
            /** Actor */
            actor: string;
            /** Reason */
            reason: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WazuhStatus */
        WazuhStatus: {
            /** Enabled */
            enabled: boolean;
            /** Reachable */
            reachable: boolean;
            /** Last Poll At */
            last_poll_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Lag Seconds */
            lag_seconds: number | null;
            /** Events Ingested Total */
            events_ingested_total: number;
            /** Events Dropped Total */
            events_dropped_total: number;
            /** Last Error */
            last_error: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_v1_events_get: {
        parameters: {
            query?: {
                source?: string | null;
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_raw_event_v1_events_raw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawEventAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_v1_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                severity_gte?: string | null;
                entity_id?: string | null;
                opened_after?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_incident_v1_incidents__incident_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    add_note_v1_incidents__incident_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRef"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_responses_v1_responses_get: {
        parameters: {
            query?: {
                incident_id?: string | null;
                status?: string | null;
                classification?: string | null;
                kind?: string | null;
                /** @description ISO 8601 datetime; return actions proposed after this time */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_response_v1_responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionProposeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionProposed"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    execute_response_v1_responses__action_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionExecuted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    revert_response_v1_responses__action_id__revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionExecuted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lab_assets_v1_lab_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabAssetOut"][];
                };
            };
        };
    };
    register_lab_asset_v1_lab_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabAssetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabAssetOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deregister_lab_asset_v1_lab_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attack_catalog_v1_attack_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackCatalog"];
                };
            };
        };
    };
    get_entity_v1_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_entity_v1_entities_get: {
        parameters: {
            query: {
                kind: components["schemas"]["EntityKind"];
                natural_key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_v1_detections_get: {
        parameters: {
            query?: {
                incident_id?: string | null;
                rule_id?: string | null;
                rule_source?: components["schemas"]["DetectionRuleSource"] | null;
                since?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wazuh_status_v1_wazuh_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WazuhStatus"];
                };
            };
        };
    };
    list_evidence_requests_v1_evidence_requests_get: {
        parameters: {
            query?: {
                incident_id?: string | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRequestList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collect_evidence_request_v1_evidence_requests__request_id__collect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_evidence_request_v1_evidence_requests__request_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocked_observables_v1_blocked_observables_get: {
        parameters: {
            query?: {
                active?: boolean | null;
                value?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedObservableList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
